<!-- This script contains code to build a web page with a form. It includes a PHP code to dynamically generate the html to display one checkbox for each of the events currently held in the EGN_events database table within the form. The user can select one or more events that they are interested in booking by clicking the checkboxes. Use the browser to look at the structure of the html generated by the php code.

You MUST NOT in any way change the php code provided OR the code within the FORM tags.

You MAY add Javascript for task 4.
You MAY modify the page to add your own navigation menu and link to your own stylesheet using additional html or php. However, please note that styling will not be marked for this assignment. -->
<?php
require_once('functions.php');
// check if user is logged in
$login = new Login();
$user_data = $login->check_login($_SESSION['eng_userid'], false);
?>
<!doctype html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="book_styles.css">
	<link rel="stylesheet" href="home_styles.css">
	<title>Book events</title>
</head>

<body>
	<style>
		#termsText {
			color: #FF0000;
			font-weight: bold;
		}

		#termsText.checked {
			color: black;
			font-weight: normal;
		}
	</style>
	<header>
		<nav class="navbar">
			<a href="index.php" class="logo">
				BookING SYS
			</a>
			<ul class="menu-links">
				<li><a href="bookEventsForm.php">Book an Event</a></li>
				<?php if ($user_data == true) : ?>
					<li class="join-btn"><a href="logout.php">Logout</a></li>
				<?php else : ?>
					<li><a href="login.php">Sign In</a></li>
				<?php endif; ?>
				<span id="close-menu-btn" class="material-symbols-outlined">close</span>
			</ul>
			<span id="hamburger-btn" class="material-symbols-outlined">menu</span>
		</nav>
	</header>

	<h1>Book events</h1>

	<form id="bookingForm" action="javascript:alert('form submitted');" method="get">
		<section id="bookEvents">
			<h2>Select events</h2>
			<?php

			try {
				// include the file with the function for the database connection
				require_once('functions.php');
				// get database connection
				$dbConn = getConnection();
				$sqlEvents = 'SELECT eventID, eventTitle, eventStartDate, eventEndDate, catDesc, venueName, eventPrice FROM EGN_events e INNER JOIN EGN_categories c ON e.catID = c.catID INNER JOIN EGN_venues v ON e.venueID = v.venueID ORDER BY eventTitle';

				// execute the query
				$rsEvents = $dbConn->query($sqlEvents);

				// Check if there are any results
				if (is_array($rsEvents) && count($rsEvents) > 0) {
					foreach ($rsEvents as $event) {
						$eventTitle = $event['eventTitle'];
						echo "\t<div class='item'>
								<span class='eventTitle'>" . filter_var($eventTitle, FILTER_SANITIZE_SPECIAL_CHARS) . "</span>
								<span class='eventStartDate'>{$event['eventStartDate']}</span>
								<span class='eventEndDate'>{$event['eventEndDate']}</span>
								<span class='catDesc'>{$event['catDesc']}</span>
								<span class='venueName'>{$event['venueName']}</span>
								<span class='eventPrice'>{$event['eventPrice']}</span>
								<span class='chosen'><input type='checkbox' name='event[]' value='{$event['eventID']}' data-price='{$event['eventPrice']}'></span>
							</div>\n";
					}
				} else {
					// Handle the case when there are no results
					echo "No events found.";
				}
			} catch (Exception $e) {
				echo "Problem " . $e->getMessage();
			}


			?>
		</section>
		<section id="collection">
			<h2>Collection method</h2>
			<p>Please select whether you want your chosen event ticket(s) to be delivered to your home address (a charge applies for this) or whether you want to collect them yourself.</p>
			<p>
				Home address - &pound;7.99 <input type="radio" name="deliveryType" value="home" data-price="7.99" checked>&nbsp; | &nbsp;
				Collect from ticket office - no charge <input type="radio" name="deliveryType" value="ticketOffice" data-price="0">
			</p>
		</section>
		<section id="checkCost">
			<h2>Total cost</h2>
			Total <input type="text" name="total" size="10" readonly>
		</section>
		<section id="placeBooking">
			<h2>Place booking</h2>
			<h3>Your details</h3>
			<div id="custDetails" class="custDetails">
				Forename <input type="text" name="forename" id="forenameInput">
				Surname <input type="text" name="surname" id="surnameInput">
			</div>
			<p id='termsText'>I have read and agree to the terms and conditions
				<input type="checkbox" name="termsChkbx" onchange="updateStyle(this)">
			</p>
			<p><input type="submit" name="submit" value="Book now!" id="submitButton" disabled></p>
		</section>
	</form>
	<!-- Here you need to add Javascript or a link to a script (.js file) to process the form as required for task 4 of the assignment -->
	<script>
		function updateStyle(checkbox) {
			var termsText = document.getElementById('termsText');
			if (checkbox.checked) {
				termsText.classList.add('checked');
				updateSubmitButton(checkbox);
			} else {
				termsText.classList.remove('checked');
				updateSubmitButton(checkbox);
			}
		}

		function updateSubmitButton(checkbox) {
			var submitButton = document.getElementById('submitButton');
			submitButton.disabled = !checkbox.checked;
		}

		function updateSubmitButton() {
			var forenameInput = document.getElementById('forenameInput').value.trim();
			var surnameInput = document.getElementById('surnameInput').value.trim();
			var termsCheckbox = document.getElementsByName('termsChkbx')[0];
			var submitButton = document.getElementById('submitButton');

			// Check if forename and surname are not empty
			var isValidForename = forenameInput !== '';
			var isValidSurname = surnameInput !== '';

			// Check if at least one event is selected
			var isValidEvent = termsCheckbox.checked;

			// Enable or disable the submit button based on the conditions
			submitButton.disabled = !(isValidForename && isValidSurname && isValidEvent);
		}

		document.addEventListener('DOMContentLoaded', function() {
			// Event handler for checkboxes
			var checkboxes = document.querySelectorAll('input[type="checkbox"]');
			checkboxes.forEach(function(checkbox) {
				checkbox.addEventListener('change', updateTotalCost);
			});

			// Event handler for radio buttons
			var radioButtons = document.querySelectorAll('input[type="radio"]');
			radioButtons.forEach(function(radioButton) {
				radioButton.addEventListener('change', updateTotalCost);
			});

			// Event handler for text inputs
			var textInputs = document.querySelectorAll('input[type="text"]');
			textInputs.forEach(function(textInput) {
				textInput.addEventListener('keyup', updateTotalCost);
			});

			// Function to update total cost
			function updateTotalCost() {
				var totalCost = 0;

				// Calculate total cost based on selected events
				checkboxes.forEach(function(checkbox) {
					if (checkbox.checked) {
						totalCost += parseFloat(checkbox.getAttribute('data-price'));
					}
				});

				// Add delivery cost based on selected delivery method
				var selectedDelivery = document.querySelector('input[name="deliveryType"]:checked');
				if (selectedDelivery) {
					totalCost += parseFloat(selectedDelivery.getAttribute('data-price'));
				}

				// Display total cost in the input field
				var totalInput = document.querySelector('input[name="total"]');
				if (totalInput) {
					totalInput.value = totalCost.toFixed(2);
				}

				// Enable or disable the submit button based on the conditions
				var submitButton = document.getElementById('submitButton');
				var isValidForename = document.getElementById('forenameInput').value.trim() !== '';
				var isValidSurname = document.getElementById('surnameInput').value.trim() !== '';
				var isValidEvent = checkboxes.some(function(checkbox) {
					return checkbox.checked;
				});

				submitButton.disabled = !(isValidForename && isValidSurname && isValidEvent);
			}
		});
	</script>
</body>

</html>